image: node:22.8-bullseye-slim

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 
    - if: $CI_COMMIT_BRANCH == "staging"
    - if: $CI_MERGE_REQUEST_ID # For merge requests
    - if: $CI_COMMIT_TAG 

stages:
  - build
  - test
  - lint
  - release

client_build:
  stage: build
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run build
  cache:  
    key: $CI_COMMIT_REF_SLUG
    paths:
      - client/.npm/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - client/dist/

bundlesize-client:
  stage: build
  dependencies:
    - client_build
  script:
    - npx bundlesize2
  needs:
    - client_build

server_test:
  stage: test
  before_script:
    - npm install
  script:
    - cd server
    - npm ci --cache .npm --prefer-offline
    - npm run test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - server/.npm/

client_lint:
  stage: lint
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run lint
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - client/.npm/

server_lint:
  stage: lint
  script:
    - cd server
    - npm ci --cache .npm --prefer-offline
    - npm run lint
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - server/.npm/

build-app-archive:
  stage: release
  variables:
    RELEASE_FILE: release-$CI_PROJECT_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA.tar.gz
  dependencies:
    - client_build
  rules:
    - if: $CI_COMMIT_TAG  
  before_script:
    - cd server
    - npm ci --omit=dev  
    - cd ..
  script:
    - tar -zcvf $RELEASE_FILE client/dist server/node_modules server/*.js server/controllers server/db server/routes server/app.mjs server/node_modules
  artifacts:
    expire_in: 7 days
    paths:
      - $RELEASE_FILE